name: "OpenAI"
version: "1.0.0"
description: "Generates text responses using OpenAI API"

settings:
  - name: "apiKey"
    type: "string"
    required: true
    description: "OpenAI API key"
  - name: "enabled"
    type: "boolean"
    default: true
    description: "Enable/disable the node"
  - name: "model"
    type: "string"
    default: "gpt-4"
    description: "OpenAI model to use"
  - name: "temperature"
    type: "float"
    default: 0.7
    description: "Response randomness (0-1)"

inputs:
  - name: "prompt"
    type: "string"
    required: true
    description: "Text prompt for generation"

outputs:
  - name: "response"
    type: "string"
    description: "Generated text response"

execution:
  timeout: 60
  retry:
    attempts: 3
    delay: 2 