name: "Slack"
version: "1.0.0"
description: "Sends notifications to Slack channels"

settings:
  - name: "webhook"
    type: "string"
    required: true
    description: "Slack webhook URL for sending messages"
  - name: "enabled"
    type: "boolean"
    default: true
    description: "Enable/disable the node"
  - name: "username"
    type: "string"
    default: "AI Bot"
    description: "Bot username in Slack"
  - name: "icon_emoji"
    type: "string"
    default: ":robot_face:"
    description: "Bot icon emoji"

inputs:
  - name: "message"
    type: "string"
    required: true
    description: "Message to send to Slack"
  - name: "channel"
    type: "string"
    required: false
    description: "Optional channel override"

outputs:
  - name: "status"
    type: "string"
    description: "Message delivery status"
  - name: "timestamp"
    type: "string"
    description: "Message timestamp"

execution:
  timeout: 10
  retry:
    attempts: 3
    delay: 1 