name: "DALL·E"
version: "1.0.0"
description: "Generates images from text prompts using DALL·E API"

settings:
  - name: "apiKey"
    type: "string"
    required: true
    description: "OpenAI API key for DALL·E access"
  - name: "enabled"
    type: "boolean"
    default: true
    description: "Enable/disable the node"

inputs:
  - name: "prompt"
    type: "string"
    required: true
    description: "Text prompt to generate image from"

outputs:
  - name: "image"
    type: "string"
    description: "Base64 encoded generated image"

execution:
  timeout: 30
  retry:
    attempts: 3
    delay: 5 