name: "Google Drive"
version: "1.0.0"
description: "Saves files to Google Drive"

settings:
  - name: "folder"
    type: "string"
    required: true
    description: "Target folder path in Google Drive"
  - name: "enabled"
    type: "boolean"
    default: true
    description: "Enable/disable the node"
  - name: "credentials_file"
    type: "string"
    required: true
    description: "Path to Google Drive credentials JSON file"
  - name: "mime_type"
    type: "string"
    default: "image/png"
    description: "Default MIME type for uploaded files"

inputs:
  - name: "file_data"
    type: "string"
    required: true
    description: "File data to save (base64 or path)"
  - name: "file_name"
    type: "string"
    required: false
    description: "Optional custom file name"
  - name: "mime_type"
    type: "string"
    required: false
    description: "Optional MIME type override"

outputs:
  - name: "file_path"
    type: "string"
    description: "Path to saved file in Google Drive"
  - name: "file_id"
    type: "string"
    description: "Google Drive file ID"
  - name: "share_url"
    type: "string"
    description: "Shareable URL for the file"

execution:
  timeout: 30
  retry:
    attempts: 3
    delay: 2
  concurrent_uploads: 5 